### ISSUE TITLE
Installation failed on a fresh Debian 12 VM

### ISSUE THREAD

**Issue by dypsilon** [runlevel-4/firefly-iii-automation#14]
Hi, I tried to use the script on a relatively fresh Debian 12 VM and everything went fine until the point of `Creating a "firefly-iii/data-importer" project at "./data-importer"`. After this the script ran into the errors 

```
cp: cannot stat 'firefly-iii/data-importer/.env.example': No such file or directory
Creating firefly database environment...

Enter your MySQL root password.  If you don't have one, just hit Enter.
firefly-iii-automation/installlampwithfirefly.sh: 126: cannot open /root/firefly-iii-automation/mysql_setup.sql: No such file
cp: cannot stat '/root/firefly-iii-automation/.env': No such file or directory
cp: cannot stat '/root/firefly-iii-automation/apache2.conf': No such file or directory
ERROR: Module php7.4 does not exist!
Considering dependency mpm_prefork for php8.2:
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Module mpm_prefork already enabled
Considering conflict php5 for php8.2:
Module php8.2 already enabled
Enabling module rewrite.
To activate the new configuration, you need to run:
  systemctl restart apache2

[2023-12-04 00:03:25] local.ERROR: Exception is: {"class":"Illuminate\\Database\\QueryException","errorMessage":"SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: Name or service not known (Connection: mysql, SQL: select * from information_schema.tables where table_schema = firefly and table_name = migrations and table_type = 'BASE TABLE')","time":"Mon, 04 Dec 2023 00:03:25 +0100","file":"\/var\/www\/html\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":760,"code":2002,"version":"6.0.5","url":"http:\/\/localhost","userAgent":"Symfony","json":true,"method":"GET"}  
[2023-12-04 00:03:25] local.WARNING: [Bcc] Could not email or log the error. Please validate your email settings, use the .env.example file as a guide.  
[2023-12-04 00:03:25] local.ERROR: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: Name or service not known (Connection: mysql, SQL: select * from information_schema.tables where table_schema = firefly and table_name = migrations and table_type = 'BASE TABLE') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: Name or service not known (Connection: mysql, SQL: select * from information_schema.tables where table_schema = firefly and table_name = migrations and table_type = 'BASE TABLE') at /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
[stacktrace]
#0 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(899): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(878): Illuminate\\Database\\Connection->tryAgainIfCausedByLostConnection()
#2 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(722): Illuminate\\Database\\Connection->handleQueryException()
#3 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\\Database\\Connection->run()
...
```

And after that a lot of PHP errors:
```
Now seeding the database...
[2023-12-04 00:04:05] local.ERROR: Exception is: {"class":"Illuminate\\Database\\QueryException","errorMessage":"SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: Name or service not known (Connection: mysql, SQL: select * from information_schema.tables where table_schema = firefly and table_name = migrations and table_type = 'BASE TABLE')","time":"Mon, 04 Dec 2023 00:04:05 +0100","file":"\/var\/www\/html\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":760,"code":2002,"version":"6.0.5","url":"http:\/\/localhost","userAgent":"Symfony","json":true,"method":"GET"}  
[2023-12-04 00:04:05] local.WARNING: [Bcc] Could not email or log the error. Please validate your email settings, use the .env.example file as a guide.  
[2023-12-04 00:04:05] local.ERROR: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: Name or service not known (Connection: mysql, SQL: select * from information_schema.tables where table_schema = firefly and table_name = migrations and table_type = 'BASE TABLE') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: Name or service not known (Connection: mysql, SQL: select * from information_schema.tables where table_schema = firefly and table_name = migrations and table_type = 'BASE TABLE') at /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
[stacktrace]
#0 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(899): Illuminate\\Database\\Connection->runQueryCallback()

```
I will go try to install using Docker, thought the report might help...

**Comment by runlevel-4** [comment]
@dypsilon I just committed a pull request to have the latest data import version always installed.  So try again and see if that works :)

**Comment by runlevel-4** [comment]
Nevermind, I see.  In the first line where it could not find the example file.  I may end up retiring this script anyway since firefly-iii has its own official docker option now, a long with the importer.

https://docs.firefly-iii.org/how-to/firefly-iii/installation/docker/
